
url: "https://mega-site-dark.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
name: 
title: # the name of your site, e.g. ACME Corp.
data_dir: _data
include:
  - sitemap.xml
  - robots.txt
  - _header
plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-admin
  - jekyll_picture_tag
picture:
  source: "/"
  output: "assets/images/opt"