builder: jekyll
defaults:
  - scope:
      path: "assets/mega_img"
    values:
      image: true

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
name: prelend
title: "Список даркнет-площадок" # the name of your site, e.g. ACME Corp.
data_dir: _data
mega_dir: mega
bs_dir: bs
include:
  - sitemap.xml
  - robots.txt
  - _header
plugins:
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-admin
  - jekyll_picture_tag
picture:
  source: "/"
  output: "assets/images/opt"